/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import controladores.ControladorLogin;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

/**
 *
 * @author VICTOR
 */
public class VistaCrearUsuario extends javax.swing.JFrame {

    /**
     * Creates new form VistaCrearUsuario
     */
    public VistaCrearUsuario() {

        initComponents();

        this.ocultarPassword.setVisible(false);
        //cambiar el icono de la taza de java a un logotipo
        cambiarIcono();

        
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        // Agregar un WindowListener para capturar el evento de cierre
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                confirmarCierre(); // Llamar al método personalizado
            }
        });
    }

    private void confirmarCierre() {
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "¿Estás seguro de que deseas cerrar?",
                "Confirmación",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            realizarAccionesAntesDeCerrar(); // Ejecutar acciones personalizadas
            dispose(); // Cerrar la ventana
        } else {
            System.out.println("Cierre cancelado.");
        }
    }

    private void realizarAccionesAntesDeCerrar() {
        // Aquí puedes agregar cualquier lógica adicional, como guardar archivos o liberar recursos.
       ControladorLogin.mostrar();
    }
    
    
    
    

    private void cambiarIcono() {
        ImageIcon icono = new ImageIcon(getClass().getResource("/img/logoHospital.jpg"));
        Image imagen = icono.getImage();

        this.setIconImage(imagen);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        panelRound1 = new vistas.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        panelRound2 = new vistas.PanelRound();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellidoPaterno = new javax.swing.JLabel();
        jLabelApellidoMaterno = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        jLabelTipoDeUsuario = new javax.swing.JLabel();
        panelRound3 = new vistas.PanelRound();
        txtNombre = new javax.swing.JTextField();
        panelRound4 = new vistas.PanelRound();
        txtApellidoPaterno = new javax.swing.JTextField();
        panelRound5 = new vistas.PanelRound();
        txtApellidoMaterno = new javax.swing.JTextField();
        panelRound6 = new vistas.PanelRound();
        txtUsuario = new javax.swing.JTextField();
        panelRound7 = new vistas.PanelRound();
        txtPassword = new javax.swing.JPasswordField();
        panelRound8 = new vistas.PanelRound();
        txtTipoDeUsuario = new javax.swing.JTextField();
        jbnRegistrar = new javax.swing.JButton();
        ocultarPassword = new javax.swing.JLabel();
        verPassword = new javax.swing.JLabel();
        jbnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));
        jPanel4.setMinimumSize(new java.awt.Dimension(600, 700));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setPreferredSize(new java.awt.Dimension(120, 120));
        panelRound1.setRoundBottomLeft(180);
        panelRound1.setRoundBottomRight(180);
        panelRound1.setRoundTopLeft(180);
        panelRound1.setRoundTopRight(180);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/avatarCrearUsuarioNuevo.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, -1, 120));

        jPanel4.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 120, 120));

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombre.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombre.setText("Nombre");
        panelRound2.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabelApellidoPaterno.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelApellidoPaterno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelApellidoPaterno.setText("Apellido Paterno");
        panelRound2.add(jLabelApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabelApellidoMaterno.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelApellidoMaterno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelApellidoMaterno.setText("Apellido Materno");
        panelRound2.add(jLabelApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabelUsuario.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUsuario.setText("Usuario");
        panelRound2.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabelContraseña.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelContraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelContraseña.setText("Contraseña");
        panelRound2.add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabelTipoDeUsuario.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelTipoDeUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTipoDeUsuario.setText("Tipo de Usuario");
        panelRound2.add(jLabelTipoDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        panelRound3.setRoundBottomLeft(10);
        panelRound3.setRoundBottomRight(10);
        panelRound3.setRoundTopLeft(10);
        panelRound3.setRoundTopRight(10);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setBackground(new java.awt.Color(242, 242, 242));
        txtNombre.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombre.setBorder(null);
        txtNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        panelRound3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 348, 30));

        panelRound2.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 360, 30));

        panelRound4.setRoundBottomLeft(10);
        panelRound4.setRoundBottomRight(10);
        panelRound4.setRoundTopLeft(10);
        panelRound4.setRoundTopRight(10);
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtApellidoPaterno.setBackground(new java.awt.Color(242, 242, 242));
        txtApellidoPaterno.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtApellidoPaterno.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtApellidoPaterno.setBorder(null);
        panelRound4.add(txtApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 348, 30));

        panelRound2.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 360, -1));

        panelRound5.setRoundBottomLeft(10);
        panelRound5.setRoundBottomRight(10);
        panelRound5.setRoundTopLeft(10);
        panelRound5.setRoundTopRight(10);
        panelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtApellidoMaterno.setBackground(new java.awt.Color(242, 242, 242));
        txtApellidoMaterno.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtApellidoMaterno.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtApellidoMaterno.setBorder(null);
        panelRound5.add(txtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 348, 30));

        panelRound2.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 360, -1));

        panelRound6.setRoundBottomLeft(10);
        panelRound6.setRoundBottomRight(10);
        panelRound6.setRoundTopLeft(10);
        panelRound6.setRoundTopRight(10);
        panelRound6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.setBackground(new java.awt.Color(242, 242, 242));
        txtUsuario.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUsuario.setBorder(null);
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        panelRound6.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 348, 30));

        panelRound2.add(panelRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 360, -1));

        panelRound7.setRoundBottomLeft(10);
        panelRound7.setRoundBottomRight(10);
        panelRound7.setRoundTopLeft(10);
        panelRound7.setRoundTopRight(10);
        panelRound7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPassword.setBackground(new java.awt.Color(242, 242, 242));
        txtPassword.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtPassword.setBorder(null);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        panelRound7.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 348, 30));

        panelRound2.add(panelRound7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 360, -1));

        panelRound8.setRoundBottomLeft(10);
        panelRound8.setRoundBottomRight(10);
        panelRound8.setRoundTopLeft(10);
        panelRound8.setRoundTopRight(10);
        panelRound8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTipoDeUsuario.setBackground(new java.awt.Color(242, 242, 242));
        txtTipoDeUsuario.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtTipoDeUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTipoDeUsuario.setBorder(null);
        panelRound8.add(txtTipoDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 348, 30));

        panelRound2.add(panelRound8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 360, -1));

        jbnRegistrar.setBackground(new java.awt.Color(231, 231, 231));
        jbnRegistrar.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        jbnRegistrar.setText("REGISTRAR");
        jbnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbnRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnRegistrarActionPerformed(evt);
            }
        });
        panelRound2.add(jbnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 140, 40));

        ocultarPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/esconder.png"))); // NOI18N
        ocultarPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ocultarPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ocultarPasswordMouseClicked(evt);
            }
        });
        panelRound2.add(ocultarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 280, -1, -1));

        verPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ver_1.png"))); // NOI18N
        verPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verPasswordMouseClicked(evt);
            }
        });
        panelRound2.add(verPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 280, -1, -1));

        jbnCancelar.setBackground(new java.awt.Color(235, 9, 9));
        jbnCancelar.setFont(new java.awt.Font("Futura Md BT", 0, 18)); // NOI18N
        jbnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jbnCancelar.setText("CANCELAR");
        jbnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnCancelarActionPerformed(evt);
            }
        });
        panelRound2.add(jbnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 140, 40));

        jPanel4.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 450, 450));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void jbnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnRegistrarActionPerformed
        JOptionPane.showMessageDialog(null, "REGISTRO EXITOSO");
        controladores.ControladorLogin.cerrarVistaCrearUsuario();

    }//GEN-LAST:event_jbnRegistrarActionPerformed

    private void verPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verPasswordMouseClicked
        verPassword.setVisible(false);
        ocultarPassword.setVisible(true);
        txtPassword.setEchoChar((char) 0);
    }//GEN-LAST:event_verPasswordMouseClicked

    private void ocultarPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ocultarPasswordMouseClicked
        verPassword.setVisible(true);
        ocultarPassword.setVisible(false);
        txtPassword.setEchoChar('*');
    }//GEN-LAST:event_ocultarPasswordMouseClicked

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void jbnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnCancelarActionPerformed
        ControladorLogin.mostrar();
        ControladorLogin.cerrarVistaCrearUsuario();
    }//GEN-LAST:event_jbnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCrearUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelApellidoMaterno;
    private javax.swing.JLabel jLabelApellidoPaterno;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTipoDeUsuario;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbnCancelar;
    private javax.swing.JButton jbnRegistrar;
    private javax.swing.JLabel ocultarPassword;
    private vistas.PanelRound panelRound1;
    private vistas.PanelRound panelRound2;
    private vistas.PanelRound panelRound3;
    private vistas.PanelRound panelRound4;
    private vistas.PanelRound panelRound5;
    private vistas.PanelRound panelRound6;
    private vistas.PanelRound panelRound7;
    private vistas.PanelRound panelRound8;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTipoDeUsuario;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JLabel verPassword;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getTxtApellidoMaterno() {
        return txtApellidoMaterno;
    }

    public void setTxtApellidoMaterno(javax.swing.JTextField txtApellidoMaterno) {
        this.txtApellidoMaterno = txtApellidoMaterno;
    }

    public javax.swing.JTextField getTxtApellidoPaterno() {
        return txtApellidoPaterno;
    }

    public void setTxtApellidoPaterno(javax.swing.JTextField txtApellidoPaterno) {
        this.txtApellidoPaterno = txtApellidoPaterno;
    }

    public javax.swing.JTextField getTxtNombre() {
        return txtNombre;
    }

    public void setTxtNombre(javax.swing.JTextField txtNombre) {
        this.txtNombre = txtNombre;
    }

    public javax.swing.JPasswordField getTxtPassword() {
        return txtPassword;
    }

    public void setTxtPassword(javax.swing.JPasswordField txtPassword) {
        this.txtPassword = txtPassword;
    }

    public javax.swing.JTextField getTxtTipoDeUsuario() {
        return txtTipoDeUsuario;
    }

    public void setTxtTipoDeUsuario(javax.swing.JTextField txtTipoDeUsuario) {
        this.txtTipoDeUsuario = txtTipoDeUsuario;
    }

    public javax.swing.JTextField getTxtUsuario() {
        return txtUsuario;
    }

    public void setTxtUsuario(javax.swing.JTextField txtUsuario) {
        this.txtUsuario = txtUsuario;
    }
}
